### ISSUE TITLE
是否为项目加个LICENCE

### ISSUE THREAD

**Issue by Utaea** [Dreace/NUC-Information-Backend#2]
看到你的项目很棒，我们也有意将其稍加修改为我们学校的教务系统部署你的项目

但是我发现你的项目还没有LICENCE，为了规避风险是否可以考虑加一下LICENCE，我们会根据LICENCE进行下一步方案
谢谢

**Comment by Dreace** [comment]
已添加 GPL-3.0 LICENSE
